version: '3.5'
services:
  mysql:
    image: mysql:5.7
    command: --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION" --max_connections=1500
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin_pass'  # Пароль для пользователя root
      MYSQL_DATABASE: 'phantomcoin'    # Имя создаваемой базы данных
      MYSQL_USER: 'admin'            # Имя создаваемого пользователя
      MYSQL_PASSWORD: 'admin_pass'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --appendonly no

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  mysql_data:
