networks:
  selenoid:
    name: selenoid
services:
  mysql:
    image: mysql:5.7
    command: --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION" --max_connections=1500
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin_pass'  # Пароль для пользователя root
      MYSQL_DATABASE: 'phantomcoin'    # Имя создаваемой базы данных
      MYSQL_USER: 'admin'            # Имя создаваемого пользователя
      MYSQL_PASSWORD: 'admin_pass'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --appendonly no

  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      selenoid: null
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:latest
    networks:
      selenoid: null
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "loger:1:1"
    depends_on:
      - zookeeper
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      selenoid: null
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - selenoid
    volumes:
      - ollama_data:/root/.ollama

volumes:
  mysql_data:
  ollama_data: